### ISSUE TITLE
Installation issues on Debian 8.9

### ISSUE THREAD

**Issue by mad97231** [usbwall/usbwall#1]
Hello,
During the project installation on a **Debian version 8.9** I have the following issues:
"CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.0/Modules/FindThreads.cmake:178 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:235 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/audrey/Bureau/USBWALL/usbwall-master/_build/CMakeFiles/CMakeOutput.log".
See also "/home/audrey/Bureau/USBWALL/usbwall-master/_build/CMakeFiles/CMakeError.log"."

The project's compilation stops when it checks if the compiler accepts -pthread. See the error bellow:
"-- Check if compiler accepts -pthread - no
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message): ... "

The version of the compiler is GNU 4.9.2 : **-- The C compiler identification is GNU 4.9.2**

**Comment by Oline** [comment]
Hi,

this is a bug from cmake on Debian 8.9 when using gcc.

A working solution is here : https://stackoverflow.com/questions/24813827/cmake-failing-to-detect-pthreads-due-to-warnings/25130590#25130590

You could update your distribution to stable (Debian 9) or use clang instead of gcc.
